#!/usr/bin/env bash
#This is script
# Open /etc/passwd and read it line by line
while IFS=: read -r username _ uid _ _ home_directory _; do
    # Display username, UID, and home directory
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home_directory"
    echo "-------------------------"
done < /etc/passwd
