#!/usr/bin/env bash
#This is script

# Set IFS to colon, which is the delimiter in /etc/passwd
IFS=':'

# Read each line of /etc/passwd
while read -r USERNAME PASSWORD USER_ID GROUP_ID COMMENT HOME_DIRECTORY COMMAND_SHELL; do
    # Handle cases where COMMENT might be empty or contain commas
    COMMENT=${COMMENT//,/\,}

    # Output the formatted information for each user
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $COMMENT"
done < /etc/passwd
