#!/usr/bin/env bash
#This is script

# Assuming the log file is named 'access_log'
# Adjust the file name to match your actual log file location

awk '{print $1, $9}' access_log | sort | uniq -c | sort -nr | awk '{printf "%6d %s %s\n", $1, $2, $3}'
