#!/usr/bin/env bash
#if statement to echo "Hi" on the 9th

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done

