#!/usr/bin/env bash
# This is the script

num=1

while [ $num -le 20 ]; do
    case $num in
        4)
            echo "$num - bad luck from China" ;;
        9)
            echo "$num - bad luck from Japan" ;;
        17)
            echo "$num - bad luck from Italy" ;;
        *)
            echo "$num" ;;
    esac
    ((num++))
done
