#!/usr/bin/env bash
# while loop to print different things ar different times

num=1

while [ $num -le 20 ]
do
    case $num in
        4)
            echo "Bad luck from China"
            ;;
        9)
            echo "Bad luck from Japan"
            ;;
        17)
            echo "Bad luck from Italy"
            ;;
        *)
            echo "$num"
            ;;
    esac
    
    num=$((num + 1))
done

