#!/usr/bin/env bash
#This is script
if [[ $EUID -ne 0 ]]; then
    echo "It is recommended to run this script as root to see all processes."
fi

# Display process list with hierarchy
echo "Listing all running processes with hierarchy:"
echo "----------------------------------------------------"

# Use ps and pstree to display processes
ps -eo user,pid,ppid,stat,tty,time,cmd --sort=ppid | awk 'NR==1 || $2 != 1' | column -t

echo "\nProcess hierarchy:"
pstree -aup
