#!/usr/bin/env bash
#This is script

PID=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the PID is found
if [ -z "$PID" ]; then
    echo "No running process found for 4-to_infinity_and_beyond."
else
    # Kill the process
    kill "$PID"
    echo "Process 4-to_infinity_and_beyond with PID $PID has been terminated."
fi
