#!/usr/bin/env bash
#This is script
PID=$(ps aux | grep '[4]-to_infinity_and_beyond' | awk '{print $2}')

# Check if we have the PID and stop it
if [ -n "$PID" ]; then
    # Sending SIGTERM to the process by its PID using a different signal
    xargs kill -SIGTERM <<< "$PID"
    echo "Process stopped."
else
    echo "No matching process found."
fi
